language: java

jdk:
  - oraclejdk8

# If you need a more customizable environment running in a virtual machine, use the Sudo Enabled infrastructure
sudo: required

# If you have tests that need to run on linux
os:
  - linux 

services:  
  - docker 

# Improve Build Speed
cache:
  directories:
  - $HOME/.m2

# safelist
branches:
  only:
  - master
  
# blocklist
branches:
  except:
  - integration  

# grant the needed permission
before_install:
  - chmod +x pom.xml
  - echo -e "machine github.com\n  login $GITHUB_TOKEN" >> ~/.netrc
  - git lfs pull
  - docker-compose up -d
  
  
# This two-phase mapping is not relevant for Maven projects as Maven uses a lazy approach: 
# if dependencies are not in the local repository, they will be downloaded when required. 
# For a more idiomatic management, the first phase can be bypassed, while the second one just needs to be set:
install: true
script:
    - mvn install -Dmaven.javadoc.skip=true -B -V
    
after_success:
    - copy ./RestDemo-0.0.1-SNAPSHOT.war /usr/local/tomcat/webapps/RestDemo-0.0.1-SNAPSHOT.war
    - curl -X GET  http://127.0.0.1:8095/RestDemo-0.0.1-SNAPSHOT/security/status
