language: java
jdk:
- oraclejdk8
sudo: required
os:
- linux
services:
- docker
cache:
  directories:
  - $HOME/.m2
branches:
  except:
  - integration
before_install:
- chmod +x pom.xml
- chmod +x bin/docker_push.sh
- chmod +x bin/docker_deploy.sh
- chmod +x bin/ecs_deploy.sh
- echo -e "machine github.com\n  login $GITHUB_TOKEN" >> ~/.netrc
- git lfs pull
install: true
script:
- mvn clean install -Dmaven.javadoc.skip=true -B -V
after_success:
- pwd
- bin/docker_push.sh
- bin/docker_deploy.sh
env:
  global:
  - AWS_DEFAULT_REGION=us-east-2
  - IMAGE_NAME=jetty_rest_sample
  - REMOTE_IMAGE_URL=961617510908.dkr.ecr.us-east-2.amazonaws.com/jetty_rest_sample:latest
  - ECS_TASK_DEFINITION=jettytask4:1
  - ECS_SERVICE_NAME=jettyservice
  - ECS_CLUSTER_NAME=jetty05
  - secure: boHkyMxDV7IHx4yx2KmQuUwHF4mJuw9K4a6jkeZSYkkAaaDyXtWw2pp9Yc+/IAwvMJYXxFYdUmaT66gB99P+GWckRaLyvvDtkKoOSm89jYFQoFGkpbvqFgVRkE1DrdtLFLEvgzhKyPKhWdCAJx/wbrd0AJ+up4g14Jjg/8je5hdt0j0TZN6Jwwq1TLqVP8+xzELmkS6YXP25r4qYKJcOcK/VUpKuBjAD4CledyT4QWPNiRxDpTs6q9EPWZOGCZq2Atjnmf9z2HeZulnSex+sG64hxlpPe8+Qf7dr1S5nBL2aDsnE9GEj5wqxweBuilTod/Ov2rtjgyb1voiCUYSGiEdQ0b7YcpDPVxkuo+XTsmw36t6wxLLIf2hbjro7tlh4uDv+t4zzEaP9pVyztRrpUENlf1xeXI9So5x3In3gcPL6z+gt45j4NYMN/c4170NwXRT/EX9772qfUNpoXcVDYCzgLAm7eNPy7g9nSP67+MRMyRthIgt6HaabhGNb0ppOLoVfIm2oc54x6PVHa9nq+fB8Bz7C8fZs4kDHBpMA7TKMsSArlLSonrooZkenNpppHE8tXxl7FjlR9hhgTYu6IEULychRnUfDooRjnlcYAXHIPekwXkQ8z5EMqSEjLa4daQMxVln2X3muLItI+tBtJF4Tp8RApUVGd3aWwKtPWNU=
  - secure: YizTiQpW6hMJSvYl6v4Iiq4Cei+NEHtsHV1mvhwHH5bXpzMCAsn9qS4EydfswJOBKrDgQcXiXnqKhIm/CpLmD/3cAIvFZCYz2XjIATjRgk8xgHOL0Hc1orqwuW6F1sHVMf1oVKx/U9u0+x/5vL+VJD4V668eUXWIwuR5o1iU/jpg0V+3UUTQ6MXydkVxzKZRsgY7wmNJLdKtXWkSytP1RqGie6gb7BTT8hlFw9vegj7Nc/zYiK4L7QlvP4AVgcs5baFcKZScsEDP1eA3GT0zM+RSW/BdNu9oVlDuAKsIxgHVuSwEemGJR18/zA1GeWxjY1xKOIlkmvMws81yidLlPOm3PwX8vqrPc5bxtkq+JBJ7G5L9++f7mnxUm9O7rgV+fEQT5gBf/e2IG83DCwuCoamBgy+vcKlt0QjKxp9fByk9IS4cS72CoatxwzPnKDbNwOzKWW0Nsxb35sUKIKAYGpyFx3VzZi2FUeGkpVC/ieFIgRq4G1DruP972jLGbUjUQIy1K8M6jj6a6Y/n9FcXdU3cMx0Rokz7sARV6T9y/TGPPyvy+ixKu6+v5MYXRLAnfkGQ3N0pVb2+OPqpNK4TtlT4jTeY/vbgNqT33Gbc3his8NUvfu60vGH7fFKqRGjgHULHgGAFHTlR8BxP/C1lRgg60wuXYgkDUP9WJ+7ZH1g=
  - secure: khPiMpVZmiVf83sA3JQ+2rtalQZ3DdNaIa3oL+zmMofBRrYI2d7NrFMPlDTpp3qiUTE44rfAaEhJsP7baljwbPdrcgiQBGZOTxSgMb3lVWfdU3mejSJsMkOr7e61d3EvguhlTKxBiToxDzxyqBPxgri/H1xtf8wJt3epMBe50zS05z0SeRSCAJ6EdK1KcrxrFlYMCYvDHnOYL8FGIdLUo6X+Aw0dsJHN5nVp8CYQjBguzplejzclzcbK9MqrxaSgL7RAtL+9lXumT9PVWf9wUMdZCngBOVFFOzGZA9udbm0+i/+GZb1Hd0FosmHcXU6QCDUjcbeP//hLym/3w14ZmbED7IPB9+ziDkbfvWvACBKK+kmz+CISzuR57ArqPfxbLvICTedq81X8PF0E9rwTTZ1ane9Cv9uCfrjro2/2wT0TM75QOzU7gSISumOX5bH6PELxMaWpHpiUE14GNAt70LjEGcgtH/Kn1+1OOi36+cZ0WPT2hyNqngCCr/ccEa4gwZDz9bnH5gKz7t5ya36ZB9wfawf+Hu0sKOk+YNufU6PnuhmL7hbEaaspNWuOp4vH6QBh/U7IkmV6sbtAYbTYSMEj6ynNXIxDpgCiLsZzZg0bekxeKBm9ZOyFaP911Ii4kRXpy5j1fJ0W//gNYSbtJHb9Oi3LwXMMhWpc4fN/ZWM=
