os:
  - linux
services:
  - docker
language: java
jdk:
  - oraclejdk7
sudo: false

# Improve Build Speed
cache:
  directories:
  - $HOME/.m2

# grant the needed permission
before_install:
  - chmod +x pom.xml

# This two-phase mapping is not relevant for Maven projects as Maven uses a lazy approach: 
# if dependencies are not in the local repository, they will be downloaded when required. 
# For a more idiomatic management, the first phase can be bypassed, while the second one just needs to be set:
install: true
script:
    - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V