language: java

jdk:
  - oraclejdk8

# If you need a more customizable environment running in a virtual machine, use the Sudo Enabled infrastructure
sudo: required

# If you have tests that need to run on linux
os:
  - linux 

services:  
  - docker 

# Improve Build Speed
cache:
  directories:
  - $HOME/.m2

# safelist
branches:
  only:
  - master
  
# blocklist
branches:
  except:
  - integration  

# grant the needed permission
before_install:
  - chmod +x pom.xml
  - echo -e "machine github.com\n  login $GITHUB_TOKEN" >> ~/.netrc
  - git lfs pull
  
# This two-phase mapping is not relevant for Maven projects as Maven uses a lazy approach: 
# if dependencies are not in the local repository, they will be downloaded when required. 
# For a more idiomatic management, the first phase can be bypassed, while the second one just needs to be set:
install: true
script:
    - mvn install -Dmaven.javadoc.skip=true -B -V
    
after_success:
    - pwd
    - docker build -t jetty_example/myjetty9 .
    #- docker run -p 8778:8080 jetty_example/myjetty9 
    #- curl -X GET  http://127.0.0.1:8778/security/status
    #- docker ps -a | awk '{ print $1,$2 }' |grep jetty|awk '{ print $1 }'|xargs docker stop
    #- docker ps -a | awk '{ print $1,$2 }' |grep jetty|awk '{ print $1 }'|xargs docker rm
    - pip install --user awscli # install aws cli w/o sudo
    - export PATH=$PATH:$HOME/.local/bin # put aws in the path
    - eval $(aws ecr get-login --region us-east-2) #needs AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY envvars
    




    