version: '2'

services:
  tomcat:
    image: tomcat
    ports:
       - "8095:8095"
    volumes:
       - .target/RestDemo-0.0.1-SNAPSHOT.war:/usr/local/tomcat/webapps/RestDemo-0.0.1-SNAPSHOT.war

# curl -X GET  http://localhost:8080/RestDemo/security/status